import { ViewTransitions } from "next-view-transitions";

import { DeviceProvider } from "@/context/DeviceContext";
import LenisProvider from "@/context/LenisContext";

import Header from "@/components/Header/Header";

import "./globals.css";
import "./fonts.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en">
        <DeviceProvider>
          <body>
            <LenisProvider>
              <Header />
              {children}
            </LenisProvider>
          </body>
        </DeviceProvider>
      </html>
    </ViewTransitions>
  );
}
